volumes:
  tesla_ble_mqtt:
    external: true

services:
  tesla_ble_mqtt:
    container_name: tesla_ble_mqtt
    image: "tesla-local-control/tesla_ble_mqtt:latest"


    # Configuration Settings have been moved to the "stack.env" file
    env_file:
      - stack.env

    network_mode: host

    # TODO:  Needed to open the Bluetooth dongle to send commands to the car
    privileged: true
    # TODO: Needed to open the Bluetooth device
    tty: true

    # TODO : Why?
    stdin_open: true

    # TODO : still valid?
    working_dir: /share/tesla_ble_mqtt

    volumes:
      - tesla_ble_mqtt:/share/tesla_ble_mqtt
      - /run/dbus:/run/dbus

    # TODO: most likely not needed to overwrite the image's default
    entrypoint: "/app/run.sh"

    restart: no
    #restart: unless-stopped
